language: go
go:
  - 1.11.x
  - 1.12.x

script:
  - env GO111MODULE=on go test . -cover
  - env GO111MODULE=on go test . -bench=.

notifications:
  email: false
  slack:
    secure: Z/lSug2n7osvNma4XLm+ZNv0V3RUChxlL/9TJpyb9NLI4lK35X8c6MPVq/ArxdGB1ZL5lJEznt76LDhub3iHzPlsRSn0Lq075RLtmkgFTbaOPFdSX3bcnGN9Adq9eJ2Ir4SyJHpj1Qnps29oqO4+zaQZUO94uqNLbq+QK/0QuzM/UY75ckjkfasbORNrLvA8rYGSofI1MlZxIxEEB8+F0IeHrFyhR3TedEJWhXzQjTAbzAivLAH1WHjGLD+f4kTFVxILd4umQ646KWDTyZI3UI/2BNLOWbApVEYddszjdfeuHRzbeqhWUO719TL9Mnun+rCQiX44jYnhJh4rEoh/O1/mNsmj7H4kL5QoyFAT7PEOdFDQAcGlmbNm4k/+f7S+AGQPnGATp1BNBxDWxn0iXLhA4nUAxx7Q/v1j9yDxhwTUq3Dim7dVsE9eFx/s0WXhdcyExx8mejucXcmzpyflLS8mOZLcx1rP9QzHtRfZ6arNkX2q3xFg5tKwXjw+DelabmYr1KPB4/+Irfk2xqSrPPRNoci9GW5nzPCirTNBJYiDP6DCyHiw4rNjvDz7ovBAkHC9Z3yOFfKu5OR9pZPl+Isn0zOWxPkf4gKWW9qKqPF3iaM6vDxK3mqaIeqZ+nt/WcnREWZRsDqN9KrXMTQu+IvVVmDpEqPB1wJPsLCZHKI=
