language: go
go:
- 1.7.x
- 1.8.x
- 1.9.x
env:
  global:
  - SDK_VERSION="1.9.60"
before_script:
- SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-$SDK_VERSION.zip
- wget $SDK_URL -nv
- unzip -q go_appengine_sdk_linux_amd64-$SDK_VERSION.zip
script:
- "./go_appengine/goapp build ."
notifications:
  slack:
    secure: Z/lSug2n7osvNma4XLm+ZNv0V3RUChxlL/9TJpyb9NLI4lK35X8c6MPVq/ArxdGB1ZL5lJEznt76LDhub3iHzPlsRSn0Lq075RLtmkgFTbaOPFdSX3bcnGN9Adq9eJ2Ir4SyJHpj1Qnps29oqO4+zaQZUO94uqNLbq+QK/0QuzM/UY75ckjkfasbORNrLvA8rYGSofI1MlZxIxEEB8+F0IeHrFyhR3TedEJWhXzQjTAbzAivLAH1WHjGLD+f4kTFVxILd4umQ646KWDTyZI3UI/2BNLOWbApVEYddszjdfeuHRzbeqhWUO719TL9Mnun+rCQiX44jYnhJh4rEoh/O1/mNsmj7H4kL5QoyFAT7PEOdFDQAcGlmbNm4k/+f7S+AGQPnGATp1BNBxDWxn0iXLhA4nUAxx7Q/v1j9yDxhwTUq3Dim7dVsE9eFx/s0WXhdcyExx8mejucXcmzpyflLS8mOZLcx1rP9QzHtRfZ6arNkX2q3xFg5tKwXjw+DelabmYr1KPB4/+Irfk2xqSrPPRNoci9GW5nzPCirTNBJYiDP6DCyHiw4rNjvDz7ovBAkHC9Z3yOFfKu5OR9pZPl+Isn0zOWxPkf4gKWW9qKqPF3iaM6vDxK3mqaIeqZ+nt/WcnREWZRsDqN9KrXMTQu+IvVVmDpEqPB1wJPsLCZHKI=
