version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\rayyildiz\slack-dockerhub-notify

environment:
  GOVERSION: 1.19.1

init:
  - git config --global core.autocrlf input

install:
  - choco install golang --version %GOVERSION% -y
  - go get .

build: false
deploy: false

test_script:
  - go mod download
  - go build .
  - go test . -cover
  - go test . -bench=.
